Replace our own OwnedFd with io_lifetimes::OwnedFd
FIXME: This breaks compilation without the allow-unsafe-code feature:

$ cargo run -p x11rb --example shared_memory --features "libc shm"
   Compiling x11rb v0.11.1 (/home/psychon/projects/x11rb/x11rb)
error: usage of an `unsafe` block
   --> x11rb/src/rust_connection/stream.rs:467:27
    |
467 |                 .map(|fd| unsafe { OwnedFd::from_raw_fd(fd) });
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> x11rb/src/lib.rs:139:56
    |
139 | #![cfg_attr(not(feature = "allow-unsafe-code"), forbid(unsafe_code))]
    |                                                        ^^^^^^^^^^^

error: usage of an `unsafe` block
   --> x11rb/src/rust_connection/stream.rs:570:18
    |
570 |     let socket = unsafe { OwnedFd::from_raw_fd(socket) };
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `x11rb` due to 2 previous errors